# ====== MICRONAUT CONFIG ======
micronaut:
  application:
    name: backend
  server:
    netty:
      log-level: INFO

# ====== DATABASE CONFIG ======
r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://localhost:5432/real-estatetor
      username: ${POSTGRES_USERNAME:jordi}
      password: ${POSTGRES_PASSWORD:postgrespwd}
jpa.default.properties.hibernate.hbm2ddl.auto: update

netty:
  default:
    allocator:
      max-order: 3
