# ====== MICRONAUT CONFIG ======
micronaut:
  application:
    name: backend
  server:
    port: 8080
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'


# ====== DATABASE CONFIG ======
r2dbc:
  datasources:
    default:
      url: r2dbc:postgresql://localhost:5432/real-estatetor
      username: ${POSTGRES_USERNAME:jordi}
      password: ${POSTGRES_PASSWORD:postgrespwd}
jpa.default.properties.hibernate.hbm2ddl.auto: update

netty:
  default:
    allocator:
      max-order: 3

# ====== MANAGEMENT ENDPOINTS CONFIG ======
endpoints:
  all:
    enabled: true
  beans:
    sensitive: false
  routes:
    sensitive: false
  loggers:
    sensitive: false
